version: '3.8'

x-common-variables: &common-variables
  DB_HOST: mysql_db
  MYSQL_DATABASE: roots
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD

  apache:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    volumes:
      - ./proxy/conf:/etc/apache2/sites-enabled
      - ./proxy/certs:/etc/apache2/ssl
    ports:
      - "80:80"
      - "443:443"

  backend:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    restart: always
    volumes:
      - ./server/server.js:/app/server.js
      - ./server/index.js:/app/index.js
      - ./server/database:/app/database
      - ./server/models:/app/models
      - ./server/routes:/app/routes
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db

#Using root context so that we can get models from server to use in notification service
  notification_service:
    build:
      dockerfile: ./notification-service/Dockerfile
      context: "."
    depends_on:
      - mysql_db
    restart: always
    volumes:
      - ./notification-service:/usr/src/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db