/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `user` (
  `usr_id` INT AUTO_INCREMENT PRIMARY KEY,
  `usr_first_name` VARCHAR(100) NOT NULL,
  `usr_last_name`  VARCHAR(100) NOT NULL,
  `usr_username`   VARCHAR(150) NOT NULL,
  `usr_password`   VARCHAR(255) NOT NULL,
  `usr_salt`       VARCHAR(100) NOT NULL,
  `usr_avatar`     VARCHAR(150),
  `usr_balance`    DECIMAL(12,2) DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `category` (
  `cat_id` INT AUTO_INCREMENT PRIMARY KEY,
  `cat_name` VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `category` (cat_name) VALUES ('Food'), ('Utility');

CREATE TABLE IF NOT EXISTS `transaction` (
  `tra_id` INT AUTO_INCREMENT PRIMARY KEY,
  `tra_usr_id` INT NOT NULL,
  `tra_category_id` INT NULL,
  `tra_date` DATE NOT NULL,
  `tra_amount` DECIMAL(10,2) NOT NULL,
  `tra_type` ENUM('income','expense') NOT NULL,
  `tra_description` VARCHAR(255),
  `tra_recurring_frequency` ENUM('none','weekly','monthly') DEFAULT 'none',

  CONSTRAINT `FK_transaction_user`
    FOREIGN KEY (`tra_usr_id`) REFERENCES `user`(`usr_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,  

  CONSTRAINT `FK_transaction_category`
    FOREIGN KEY (`tra_category_id`) REFERENCES `category`(`cat_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
