version: '3.8'

x-common-variables: &common-variables
  DB_HOST: mysql_db
  MYSQL_DATABASE: roots_test
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup-test.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD

  # db-test:

  #   environment:
  #     POSTGRES_DB: app
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: app
