name: activity09c

services:
  proxy:
    image: nginx:latest # Use a pre-built image from Docker Hub
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template

  backend:
    build: ./backend # Use the Dockerfile in the backend folder to build the image, instead of using one from Docker Hub
    restart: unless-stopped
    volumes: # If we just send ./backend then it will overwrite the dependencies folder in the container.
      - ./backend/app.js:/app/app.js
      - ./backend/public:/app/public

  frontend:
    image: httpd:latest # Use a pre-built image from Docker Hub
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/local/apache2/htdocs # Any changes that happen here will be reflected in the container.